language: csharp
mono: none
dotnet: 2.1.700
env:
  global:
    - CODACY_COVERAGE_VERSION=1.0.3
    - NODE_JS_VERSION="10.18"
before_install:
  - nvm install $NODE_JS_VERSION
  - node --version
install:
  - dotnet restore src/PockyBot.NET.sln
  - dotnet build src/PockyBot.NET/PockyBot.NET.csproj
jobs:
  include:
    - stage: test
      script: dotnet test src/PockyBot.NET.Tests/PockyBot.NET.Tests.csproj
    - stage: deploy
      skip_cleanup: true
      provider: script
      script: chmod +x ./deploy.sh && ./deploy.sh $NUGET_API_KEY
      if: branch = master
    - stage: cover
      provider: script
      script: chmod +x ./cover.sh && ./cover.sh
